@hostname = {{$dotenv HOST_NAME}}
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}

###

GET http://{{host}}/ HTTP/1.1

###

GET http://{{host}}/blogs HTTP/1.1

###

GET http://{{host}}/blogs/create HTTP/1.1

###

GET http://{{host}}/doesnt-exist HTTP/1.1