@hostname = {{$dotenv HOST_NAME}}
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}

###

GET http://{{host}}/login HTTP/1.1

###

POST http://{{host}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "test123"
}

###

GET http://{{host}}/signup HTTP/1.1


# Signup and signup validations

### Valid request

POST http://{{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "name": "aavee",
    "email": "user@test5.com",
    "password": "test123"
}

### Empty json

POST http://{{host}}/signup HTTP/1.1
Content-Type: application/json

{}

### name missing

POST http://{{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "email": "user@test4.com",
    "password": "test123"
}

### email missing

POST http://{{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "name": "aavee",
    "password": "test123"
}

### password missing

POST http://{{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "name": "aavee",
    "email": "user@test4.com"
}

### invalid email

POST http://{{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "name": "aavee",
    "email": "useest4.com",
    "password": "test123"
}

### invalid password

POST http://{{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "name": "aavee",
    "email": "user@test4.com",
    "password": "short"
}